---
# tasks file for dev-role2
#- name: Facts
#     block:

- name: Get instances facts
  ec2_instance_facts:
   aws_access_key: "{{ec2_access_key}}"
   aws_secret_key: "{{ec2_secret_key}}"
   region: "{{ region }}"
  register: result

#- name: Instances ID
#  debug:
#    msg: "ID: {{ item.instance_id }} - State: {{ item.state.name }} - Public DNS: {{ item.public_dns_name }}"
#    loop: "{{ result.instances }}"

#tags: always


#- name: Provisioning EC2 instances
#  block:

#- name: Upload public key to AWS
#  ec2_key:
#    name: "{{ key_name }}"
#    key_material: "{{ lookup('file', '/Users/julianosilva/.ssh/{{ key_name }}.pub') }}"
#    region: "{{ region }}"
#    aws_access_key: "{{ec2_access_key}}"
#    aws_secret_key: "{{ec2_secret_key}}"

- name: Create security group
  ec2_group:
    name: sec_group
    description: Sec_group_for_app
    # vpc_id: 12345
    region: "{{ region }}"
    aws_access_key: "{{ec2_access_key}}"
    aws_secret_key: "{{ec2_secret_key}}"
    rules:
      - proto: tcp
        ports:
          - 22
        cidr_ip: 0.0.0.0/0

      - proto: tcp
        ports:
          - 80
        cidr_ip: 0.0.0.0/0

      - proto: tcp
        ports:
          - 443
        cidr_ip: 0.0.0.0/0

      - proto: all
        ports:
          - all
        cidr_ip: 0.0.0.0/0



  register: result_sec_group

- name: Provision instance(s)
  ec2:
    aws_access_key: "{{ec2_access_key}}"
    aws_secret_key: "{{ec2_secret_key}}"
    key_name: "{{ key_name }}"
    id: "{{ id }}"
    group_id: "{{ result_sec_group.group_id }}"
    image: "{{ image }}"
    instance_type: t2.micro
    region: "{{ region }}"
    wait: true
    count: 1
    instance_tags:
        Name: Created-By-Ansible
